### ISSUE TITLE
Please delete nsfw sites that spread vice corruption in the world so that this directory is more popular family friendly

### ISSUE THREAD

**Issue by trimechee** [OshekharO/Web-Indexer#9]
Hi, thanks for this directory but we regret the presence of nsfw sites which propagate vice, corruption, fornication vulgarity indecency aids mst sexual diseases mixture of filiation abortion in the world, imagine people we know are present on these sites and they repent and no longer want to appear on these sites which penalize their professional careers if they change horizons and no longer want to do this negative activity, I would like to share this directory with my friends, family, so please delete the nsfw section, thank you, or at least hide it at the bottom or in hided  section and not highlight it, thank you!

**Comment by OshekharO** [comment]
Sure will remove this 👍
